analyzer:
  plugins:
    - ../custom_lint

custom_lint:
  rules:
    - avoid_unused_parameters:
      exclude:
        - class_name: Exclude
          method_name: excludeMethod
        - method_name: excludeMethod
